### ISSUE TITLE
Usage without web app

### ISSUE THREAD

**Issue by willchoprojects** [aalok-sathe/libcolgraph#1]
Hi @aalok-sathe!

I was just getting started with libcolgraph and I had a few questions:

Specifically, I would like to input a base graph and the number of colours I want to use, then get out a single pairing of vertices to colours.

Something along the lines of:

### Input: 
Colours: 
```
2
```
Adjacencies:
```
6
0 1 1 1 0 0
1 0 0 0 1 0
1 0 0 0 0 0
1 0 0 0 0 0
0 1 0 0 0 1
0 0 0 0 1 0
```

### Output:
```
Vertex 0: Colour 0
Vertex 1: Colour 1
Vertex 2: Colour 1
Vertex 3: Colour 1
Vertex 4: Colour 0
Vertex 5: Colour 1
```

Do you have a suggestion/an example that would be good for this?

I'm also trying to do everything within Python so if there's a way without using the web visualization, please let me know!

Thank you!!

**Comment by aalok-sathe** [comment]
this is definitely possible using our library, but likely inefficient compared to a program that specifically addresses graph coloring. The way our library will get this done is by enumerating all possible ways to color the graph and checking which ones are valid. Once the coloring graph is constructed, you can query any node/vertex of this graph to find a valid coloring. All this can be done as a library, without the web app.
